### ISSUE TITLE
Hashes following post

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#10]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/66)

http://munews.wpengine.com/121101_mercer-to-dedicate-myers-welcome-center-friday-building-is-the-universitys-first-leed-certifi/

![screen shot 2018-01-31 at 1 13 28 pm](https://user-images.githubusercontent.com/22402707/35639571-90cdf6aa-0688-11e8-95d8-781e0e3b6b70.png)

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/66#issuecomment-362023727)

other cases: 
- http://munews.wpengine.com/120911_mercers-mcduffie-center-for-strings-and-its-namesake-to-be-featured-this-week-on-national-rad/
- http://munews.wpengine.com/120808_mcduffie-loves-macon-free-community-concert-a-pre-labor-day-gift-to-the-world-renowned-musici/
- http://munews.wpengine.com/120713_mercer-professors-selected-as-governors-teaching-fellows/
- http://munews.wpengine.com/120423_the-grand-opera-house-announces-2012-13-variety-series/

---

@Sporkyy commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/66#issuecomment-362069732)

This is editorial. Do we change this on ex/import?

See also: #68

**Comment by Sporkyy** [comment]
@maconmatt Do I remove these? And the other "sign offs"?

**Comment by Sporkyy** [comment]
http://thehalogroup.com/what-does-mean-at-the-end-of-a-press-release/

**Comment by Sporkyy** [comment]
Still an editorial decision and I'm still not removing them.

More whitelisting has improved the formatting of the example article tremendously.
