### ISSUE TITLE
-30- following posts

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#12]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68)

cases: 
- http://munews.wpengine.com/120827_mercer-law-school-welcomes-inaugural-llm-class/
- http://munews.wpengine.com/120821_princeton-review-mercer-no-8-for-intramural-involvement/
- http://munews.wpengine.com/120816_mercers-largest-entering-class-set-to-move-in-saturday/
- http://munews.wpengine.com/120806_mercer-university-names-taylor-as-2012-griffith-scholar/
- http://munews.wpengine.com/120719_peyton-anderson-foundation-awards-1-million-grant-to-fund-newsroom-in-center-for-collaborativ/
- http://munews.wpengine.com/110818_chapel/

---

@Sporkyy commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68#issuecomment-362070208)

This is editorial. Do we make this change on ex/import?

See also: #66 

---

@maconmatt commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68#issuecomment-362070423)

What exactly is it? Where did it come from?

---

@Sporkyy commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68#issuecomment-362070515)

Vanderhoek.

---

@maconmatt commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68#issuecomment-362070605)

Wait...so it is (was) designed to be there? 

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/68#issuecomment-362072134)

As far as we can tell, yes. We don't know why it was started or why it stopped.

**Comment by Sporkyy** [comment]
I see neither technical need nor editorial desire to have them be removed. So I'm not.
