### ISSUE TITLE
Â€˜characters replacing single quotes (in Title)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#14]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/70)

http://munews.wpengine.com/120808_mcduffie-loves-macon-free-community-concert-a-pre-labor-day-gift-to-the-world-renowned-musici/
![screen shot 2018-01-31 at 1 24 56 pm](https://user-images.githubusercontent.com/22402707/35640083-287f5f4c-068a-11e8-9989-5d42bdc19a81.png)

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/70#issuecomment-362033270)

Other Cases: 
- http://munews.wpengine.com/111005_symposium/
- http://munews.wpengine.com/110920_potter/

**Comment by Sporkyy** [comment]
Fixed with html entity encoding.
