### ISSUE TITLE
Bullets as question marks

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#15]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/71)

http://munews.wpengine.com/120620_26-mercer-law-students-receive-stipends-for-summer-internships/

![screen shot 2018-01-31 at 1 29 45 pm](https://user-images.githubusercontent.com/22402707/35640354-f110d364-068a-11e8-8f98-16b245a157bc.png)

**Comment by Sporkyy** [comment]
To be clear, that's not a real HTML list `<ul><li></li></ul>` list.

Those are just bullet characters copy+pasted into the content.

Fixed with entity encoding.
