### ISSUE TITLE
ÃƒÂ© (in body)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#16]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/72)

http://munews.wpengine.com/120612_strecker-receives-national-award-for-excellence-from-nafsa/

CafÃƒÂ© Connections

[maybe  é? ](http://hcibib.org/multilingual/badchars.htm)

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/72#issuecomment-362036712)

Also on 
- http://munews.wpengine.com/110421_thecolorpurple/

**Comment by Sporkyy** [comment]
Fixed with herculean entity encoding effort.
