### ISSUE TITLE
Ã¢Â„Â¢ (in body)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#17]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/73)

http://munews.wpengine.com/120322_pre-eminent-jazz-artist-brad-leali-headlines-final-10th-anniversary-celebration-series-concer/

GrammyÃ¢Â„Â¢

**Comment by Sporkyy** [comment]
Fixed with herculean entity encoding effort.

Also, in #21 It was Grammy(R) and here it's Grammy(TM). Why? It's not my problem to fix.
