### ISSUE TITLE
links do not actually have hrefs

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#18]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/74)

http://munews.wpengine.com/120210_medcampus/

![screen shot 2018-01-31 at 1 45 13 pm](https://user-images.githubusercontent.com/22402707/35641049-0365d3f0-068d-11e8-82fe-11056212a3d6.png)

http://munews.wpengine.com/120130_phds/

(mailto: also)

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/74#issuecomment-362034633)

Other cases: 
- http://munews.wpengine.com/110824_fellow/
- http://munews.wpengine.com/110211math/

**Comment by Sporkyy** [comment]
The href attributes are now intact. But the text still runs together #25
