### ISSUE TITLE
ÃƒÂ¼  (in body)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#19]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/75)

http://munews.wpengine.com/111215_journalism-2/

Alberto IbargÃƒÂ¼en, president and CEO of Knight Foundation. 

ÃƒÂ¼ == ü

sauce: https://knightfoundation.org/about/staff/alberto-ibarguen

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/75#issuecomment-362035639)

other case: 
- http://munews.wpengine.com/110512_macon/
- http://munews.wpengine.com/110426commencement/

**Comment by Sporkyy** [comment]
Fixed with herculean entity encoding effort.
