### ISSUE TITLE
Ã¢Â€Â¦  (in body)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#20]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/76)

http://munews.wpengine.com/110919_fallconcert/

“a true visionaryÃ¢Â€Â¦one of the most important signings of my career” by Sean “Diddy” Combs.

**Ã¢Â€Â¦ == ", "**

Source: https://www.letssingit.com/janelle-mon%C3%A1e-f6216
She's been called "a different kind of diva" by Vogue Magazine and "a true visionary, one of the most important signings of my career" by Sean "Diddy" Combs.

**Comment by Sporkyy** [comment]
An ellipsis fixed with herculean entity encoding effort.
