### ISSUE TITLE
Ã‚Â®  (in body)

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#21]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/77)

http://munews.wpengine.com/110421_thecolorpurple/

GrammyÃ‚Â®-nominated 
Tony AwardÃ‚Â®-winner

**Comment by Sporkyy** [comment]
Fixed with herculean entity encoding effort.
