### ISSUE TITLE
Fix @@@ in oldest articles

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#22]
@elcopeland commented on [Thu Feb 01 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/82)

[In Excerpt]

**Comment by Sporkyy** [comment]
This will need to be stripped from the article body and used as the basis of the excerpt when present.

**Comment by Sporkyy** [comment]
@elcopeland On what page did these appear? I'm looking in the database and they're only in /newsatmercer/* and /newsatmercerae/* postings.

**Comment by cinakur** [comment]
eesh. Ummmm it was literally the first posts in that database. We didn't look at URLs, just the SQL

**Comment by Sporkyy** [comment]
@maconmatt We're not importing the News At Mercer and News At Mercer AE postings, correct.

**Comment by Sporkyy** [comment]
I might have screwed that up. Was I in the database directly? I might have been querying with

```sql
postings.path LIKE '/news%'
```

Instead of 
```sql
postings.path LIKE '/news/%'
```

**Comment by cinakur** [comment]
Yes, you were in the database directly.

**Comment by Sporkyy** [comment]
Yes, I screwed that up. So far as I know we're not importing News At Mercer (AE) postings, so I'm going to close that. @maconmatt can change that, but I don't think we've ever discussed NAM(AE) imports.
