### ISSUE TITLE
<?xml:namespace in Title

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#27]
@elcopeland commented on [Thu Feb 15 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/97)

- https://munews.wpengine.com/wp-admin/post.php?post=5576&action=edit
- https://munews.wpengine.com/wp-admin/post.php?post=5276&action=edit
- https://munews.wpengine.com/wp-admin/post.php?post=5115&action=edit

---

@elcopeland commented on [Thu Feb 15 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/97#issuecomment-365996395)

[Post List](https://munews.wpengine.com/wp-admin/edit.php?orderby=title&order=asc&s=%3C%3Fxml%3A&post_status=all&post_type=post&action=-1&m=0&cat=0&seo_filter&readability_filter&paged=1&action2=-1)

**Comment by Sporkyy** [comment]
Fixed in https://github.com/InteractiveDesignAndDevelopment/mcms-news-export/commit/26d83ddc9d7e9385cfd8a6afacdbcf87e7fff912
