### ISSUE TITLE
The Nov. 2013 articles are probably mis-dated

### ISSUE THREAD

**Issue by Sporkyy** [InteractiveDesignAndDevelopment/mcms-news-export#6]
Is this even worth fixing? I think the day and month were added to those articles in a non-standard order. There are probably other instances of the same and those just stick out.

**Comment by cinakur** [comment]
- [x] ask kyle what he thinks
- [x] if he says yes, add to final import tasks

**Comment by cinakur** [comment]
![image](https://user-images.githubusercontent.com/22402707/33573478-e2baa6dc-d903-11e7-986f-18d8cffd7fe1.png)

Answer: Kyle doesn't care. Leave it.
