### ISSUE TITLE
Add random Stock Featured Images

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#7]
(From Matt's List)
From https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/54

**Comment by Sporkyy** [comment]
These should be as generic as possible since they will be randomly assigned. They should also be numerous because they'll be use so frequently in old articles.

3000+ old articles with a majority _not_ having an article-specific image.

**Comment by maconmatt** [comment]
https://www.dropbox.com/s/pv4i0bi1ee8pawb/Images%20for%20News%20Articles.zip?dl=0

**Comment by Sporkyy** [comment]
Done. 19 total.
