### ISSUE TITLE
Boilerplate text running together

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/mcms-news-export#9]
@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/65)

example: http://munews.wpengine.com/121109_woodruff-foundation-awards-1-5-million-grant-to-fund-new-home-for-mcduffie-center-for-strings/ 

http://munews.wpengine.com/121108_university-trustees-meet-for-annual-homecoming-meeting/

052FEA4E-223F-4C51-9F73-3C4F793C9BEA

![screen shot 2018-01-31 at 1 08 14 pm](https://user-images.githubusercontent.com/22402707/35639369-089e282c-0688-11e8-80b9-c8f4a8d7ccd5.png)
![screen shot 2018-01-31 at 1 09 12 pm](https://user-images.githubusercontent.com/22402707/35639371-08b13b1a-0688-11e8-8cd0-f1863c59498b.png)

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/65#issuecomment-362023750)

other cases: 

- http://munews.wpengine.com/121005_partners-and-agencies-celebrate-construction-on-new-community-center-the-next-location-for-pr/
- http://munews.wpengine.com/120925_health-policy-analyst-john-goodman-to-kick-off-2012-13-executive-forum/
- http://munews.wpengine.com/120511_baca-receives-honorary-life-membership-in-cupa-hr/

---

@elcopeland commented on [Wed Jan 31 2018](https://github.com/InteractiveDesignAndDevelopment/wp-news/issues/65#issuecomment-362031574)

Possibly linked, might need to be its own ticket: 

Content running together. http://munews.wpengine.com/1101_promotions/

**Comment by Sporkyy** [comment]
Break `<br>` tags were whitelisted in ac934325c81ef4506aa78c2f8db11ca4557bf7e2
